DOTENV=dotenv

start-forking-node-goerli-testnet:
	$(DOTENV) -e .env.goerlitestnet -- npx hardhat node

start-forking-node-sepolia-testnet:
	$(DOTENV) -e .env.sepoliatestnet -- npx hardhat node

start-forking-node-bnb-testnet:
	$(DOTENV) -e .env.bnbtestnet -- npx hardhat node